name: Run Manually

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  chrome-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ secrets.WDIO_REPOS }}
        token: ${{ secrets.WDIO_ACCESS_TOKEN }}
        ref: ${{ secrets.BRANCH }}
        fetch-depth: 0
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.18.2
        cache: 'npm'
    - run: |
        yarn install --frozen-lockfile
    - name: Setup Chrome
      with:
        chrome-version: 122
        run: chrome --version
    - name: Run webdriver-io tests
      uses: StarUbiquitous/command-output@v1.0.1
      id: wdio
      with:
        run: yarn test:local --suite="Smoke Test"
      env:
        CAPABILITIES: chrome
        MAX_INSTANCES: 2
        R360_DASHBOARD_URL: ${{ secrets.R360_DASHBOARD_URL }}
    - name: WDIO Test Checker
      run: | 
        cat > specs-reporter.log <<EOL
        ${{ steps.wdio.outputs.stdout }}
        EOL
        if [ !  -z "$(egrep '[0-9]+\sfailed,\s' specs-reporter.log)" ]; then
          exit 1
        fi
    - uses: simple-elf/allure-report-action@v1.6
      if: always()
      with:
        allure_results: reports
        allure_report: allure-report
        allure_history: allure-history        
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: reports-html
        path: allure-report/
        retention-days: 7
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: reports-allure
        path: reports/
        retention-days: 7
