name: Trigger Cleanup Data

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  chrome-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ secrets.WDIO_REPOS }}
        token: ${{ secrets.WDIO_ACCESS_TOKEN }}
        ref: ${{ secrets.BRANCH }}
        fetch-depth: 0
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.18.2
        cache: 'npm'
    - run: |
        curl -XPOST -u "viet-evizi:${{secrets.WDIO_ACCESS_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/viet-evizi/daily-wdio/dispatches --data '{"event_type": "cleanup_data", "company": 101, "framework": "ios"}'
